site_name: June's IoT Portfolio
site_description: Weekly Hardware Builds, Code, and Logs.
site_author: Kibuku Carole June Wanjiku

theme:
  name: material
  palette:
    scheme: slate             # Defaults to dark mode
    primary: black
    accent: cyan
  font:
    text: Roboto              # Main reading text
    code: Fira Code           # Terminal/code blocks
  features:
    - navigation.tabs         # Creates top-level navigation
    - content.code.copy       # Adds a copy button to your code blocks
    - content.code.annotate   # Allows you to add inline notes to code

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences
  - pymdownx.arithmatex:     # Add this line
      generic: true

# Navigation Section
nav:
  - Build Logs:
    - Week 1:
      - Intro: index.md
      - Friday: week01/friday.md
    - Week 2:
      - Monday: week02/monday.md
      - Wednesday: week02/wednesday.md
      - Friday: week02/friday.md
      - Assignment: week02/assignment.md
    - Week 3:
      - Monday: week03/monday.md
      - Wednesday: week03/wednesday.md
    - Week 4:
      - Monday: week04/monday.md
      - Wednesday: week04/wednesday.md
    - Week 5:
      - Monday: week05/monday.md
      - Wednesday: week05/wednesday.md
    - Week 6:
      - Monday: week06/monday.md
      - Extra: week06/extra.md
      - Wednesday: week06/wednesday.md
    - Week 7:
      - Wednesday: week07/wednesday.md
      - Friday: week07/friday.md
    - Week 8:
      - Monday: week08/monday.md
      - Wednesday: week08/wednesday.md
      - Friday: week08/friday.md
    - Week 9:
      - Proposal: week09/proposal.md
      - Monday: week09/monday.md
      - Wednesday: week09/wednesday.md
      - Friday: week09/friday.md

# Style Section
extra_css:
  - stylesheets/extra.css

extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js